# Generated by Django 3.2.7 on 2021-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_type', models.CharField(max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
