# Generated by Django 3.2.7 on 2021-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='current_price',
            field=models.DecimalField(decimal_places=6, default=50, max_digits=19),
            preserve_default=False,
        ),
    ]
