# Generated by Django 3.2.7 on 2021-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
