# Generated by Django 3.2.7 on 2021-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='interval',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(max_length=10),
        ),
    ]
