# Generated by Django 3.2.7 on 2021-11-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20211027_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='interval',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
