# Generated by Django 3.2.7 on 2021-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dummy_email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='dummy email'),
        ),
    ]
