# Generated by Django 3.2.7 on 2021-10-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trade_date', models.DateField()),
                ('Order_Price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Brokerage_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Order_type', models.CharField(max_length=5)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('Stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
